apiVersion: v1
kind: Service
metadata:
  name: chimera-api
  namespace: chimera
  labels:
    app: chimera-api
spec:
  selector:
    app: chimera-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 3000
    targetPort: 3000
  type: ClusterIP
